build-aseprite:
  name: Build Aseprite
  needs: create-release
  permissions:
    contents: write
  runs-on: ${{ matrix.os }}
  strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macOS-latest ] 
